### ISSUE TITLE
Create help@bdrc.io email address and Google Group for managing inquiries from the new library & information websites.

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/archive-ops#100]

**Comment by TBRC-JimK** [comment]
@TBRC-pmench Please slack me (jim) with the suggested members

**Comment by TBRC-JimK** [comment]
@TBRC-pmench is "help" too broad? Can we call it "buda-help@bdrc.io?"  (Because we can't make a dedicated bdrc.io group or email - everything is replicated on tbrc.org as well.)

**Comment by TBRC-pmench** [comment]
The contact form will be for all inquiries to BDRC so I wanted to avoid using "buda" in the email address.

**Comment by TBRC-JimK** [comment]
I kind of get that, but that puts the burden on you  or your assistant to
route legacy calls. If you want to commit to that for like ever, then cool.

**Comment by TBRC-pmench** [comment]
I currently route everything that comes into inquiry so it shouldn't involve much of a change in terms of workload. I'll just need to check two Google groups rather than one.

**Comment by jimk-bdrc** [comment]
Seems to be up. @TBRC-pmench close if you concur.
