### ISSUE TITLE
NLM web images sync to S3:  W1NLM1596 - W1NLM2054

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/archive-ops#102]

**Comment by TBRC-Travis** [comment]
Cataloging records have been created via #108 

Web images are synced and available on tbrc.org

Waiting for dev team to complete work on bdrc.io before I send out the notification to librarians

**Comment by TBRC-Travis** [comment]
Email sent out with library.bdrc.io links

@karmagongde please have a look and let me know if you see any issues

**Comment by karmagongde** [comment]
@TBRC-Travis I have randomly checked and everyone looks good. In case during the full cataloging, if we find any issue I will let you know. Thank you.

**Comment by TBRC-Travis** [comment]
Sounds good @karmagongde.  Thank you.
