### ISSUE TITLE
NLM archive sync to RS5:  W1NLM1186 - W1NLM1235

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/archive-ops#103]
Web images already synced, just moving over the archival content via our AWS cross-bucket replication / synology syncing process.

**Comment by TBRC-Travis** [comment]
W1NLM1186 - W1NLM1235 have been synced to RS5 Archive.

I verified completeness by running rsync --dry-run comparisons between the source (NLM) and destination (RS5).

[WebArchive.sync.6.16.20.pdf](https://github.com/buda-base/archive-ops/files/4789093/WebArchive.sync.6.16.20.pdf)

**Comment by jimk-bdrc** [comment]
Looketh goodeth. But I don't need rsync verifivation - if it lied once, it would lie again. I'll accept your email that it's done.
