### ISSUE TITLE
Image not displaying on website

### ISSUE THREAD

**Issue by karmagongde** [buda-base/archive-ops#105]
The images of W00KG04060 is not displaying on the website.

**Comment by eroux** [comment]
it's an interesting case: the `dimensions.json` file lists a lot of files but there's no file in the s3 folder apart from the `dimensions.json`

**Comment by TBRC-Travis** [comment]
Weird.  Images exist in the archive but not on S3.  A simple sync will do the trick.

**Comment by TBRC-Travis** [comment]
@jimk-bdrc if want to tag team this I could walk you through fixing this.  or if you'd prefer not to bother with it I'm happy to do it.

**Comment by jimk-bdrc** [comment]
I’ll take it, and we can tag team Monday

**Comment by TBRC-Travis** [comment]
sounds good.  it will take a wee bit of processing since this is a legacy work and several images don't conform to our existing filesize restriction.  happy to tackle this together on Monday.

**Comment by jimk-bdrc** [comment]
Assigning Karma to verify that W00KG04060 displays on the tbrc.org website. It should display also on the bdrc.io viewer as well.

**Comment by karmagongde** [comment]
Displaying perfect on the website. Thanks.
