### ISSUE TITLE
W1PD96682 IA reupload

### ISSUE THREAD

**Issue by TBRC-TimB** [buda-base/archive-ops#106]
W1PD96682 is a legacy item which is under copyright that users have been asking to access via IA. The work is very large and was originally broken up into separate zip files to send to IA. This gums up the derive process. 

We need to clear out the old version of the work, and reupload a clean version.

**Comment by TBRC-TimB** [comment]
After 8 days of deriving. This is done and looks great. Currently it is listed as noindex, but is still something that can be checked out for a loan. @TBRC-Travis Do we want this to be indexed? or only accessible via direct link?
Here is the link if you want to see. 
https://archive.org/details/bdrc-W1PD96682

**Comment by TBRC-Travis** [comment]
Looks good.  Thanks Tim!
