### ISSUE TITLE
file on s3 not processing?

### ISSUE THREAD

**Issue by eroux** [buda-base/archive-ops#36]
I've uploaded `s3://manifest.bdrc.org/processing/todo/W22084.txt` an hour ago but I can't see any file appearing in `s3://manifest.bdrc.org/processing/inprocess`, I'm wondering how often the server is looking for new files?

**Comment by eroux** [comment]
ah, it just appeared!

**Comment by TBRC-JimK** [comment]
The short answer is every two minutes.
