### ISSUE TITLE
syncAnywhere - issues with readlink and mktemp commands

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/archive-ops#50]
Running bdrcSync.sh on Mac gives the following error output:

readlink: illegal option -- f
usage: readlink [-n] [file ...]

And

usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
syncOneWork.sh: line 80: $tmpf: ambiguous redirect

**Comment by TBRC-JimK** [comment]
Plese provide output of
which readlink
which mktemp

They should be 
```bash
jimk@Tseng:Cambodia$ which readlink
/usr/local/opt/coreutils/libexec/gnubin/readlink
jimk@Tseng:Cambodia$ which mktemp
/usr/local/opt/coreutils/libexec/gnubin/mktemp
```

Since we require GNU coreutils. 

Remember from 
```bash
brew info coreutils

Commands also provided by macOS have been installed with the prefix “g”.
If you need to use these commands with their normal names, you
can add a “gnubin” directory to your PATH from your bashrc like:
  PATH=“/usr/local/opt/coreutils/libexec/gnubin:$PATH”
```

**Comment by TBRC-Travis** [comment]
Ahhhh right.

This is my current situation:
```
$ which readlink
/usr/bin/readlink
$ which mktemp
/usr/bin/mktemp
```

And this is el problemo...I'll fix this.  Thanks.
