### ISSUE TITLE
Create script to check image status on BUDA

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/archive-ops#53]
From Jim:

```
https://iiifpres-dev.bdrc.io/v:bdr:I0FFY004/manifest
(you have to use the Image group ID). If it comes back 200 from curl, then the viewer will be able to display the image.  The full curl would be
-o /dev/null    WGAF about the actual output
-s for silent 
-w for write "%{http_code}\n". I guess you can report selected response variables, we want only this one.

itsAlive=$(curl -o /dev/null -s  -w "%{http_code}\n"  https://iiifpres-dev.bdrc.io/v:bdr:I1NLM1648_001/manifest)

[[ $itsAlive == "200" ]] && { echo Image group is viewable }
[[ $itsAlive == "500" ]] && { echo Image group not found or not viewable  }
```
 
_One caveat - it's on the dev system, which is sync'd intermittently from the prod system (This doesn't . Élie said he'd ask Chris to have the prod - dev feed updated daily, I don't know if that's happened, but it looks like it has_

**Comment by TBRC-Travis** [comment]
Use public module interface to grab list of image groups from a RID:

https://www.tbrc.org/public?module=work&query=work-igs&args=<RID>

**Comment by xristy** [comment]
Yes the dev system is updated daily now.

**Comment by TBRC-Travis** [comment]
https://github.com/buda-base/archive-ops/blob/master/scripts/QA/check-BUDA-image-status.sh
