### ISSUE TITLE
Remove indexing from Cambodia works

### ISSUE THREAD

**Issue by TBRC-JimK** [buda-base/archive-ops#59]
Program Management would like the Cambodia collection to not be accessible on Internet Archive. There was discussion of "darkening" the works, but Hank from IA advises this is a drastic step that requires their intervention. 

The same goal can be met in a less destructive way by setting a flag named `noindex` to `true`         In this way, the work is hidden from search results, while the owners, or others with the actual identifier (e.g. `bdrc-W1FEMC030002`) can still be controlled. (For example, setting the `noindex` flag to `false` when we decide that we can index them, or changing the publisher or other metadata  prior to indexing them.)

So the work is to run 
`ia metadata bdrc-W1FEMC030002 -m  noindex:true`

against this list

[noIndexMeList.txt](https://github.com/buda-base/archive-ops/files/4505916/noIndexMeList.txt)

The list is is json format, so you can reduce with 
`cat noIndexMeList.txt | jq .identifier`.

**Comment by TBRC-JimK** [comment]
Note also, that the Cambodia syncing process uses it own shell to sync.  You can see it on `sattva:~service/prod/DDD`
Note that this shell redirects the IA post processing to the `InternetArchive/processing/holdForIA-FEMC/` directory, to prevent IA upload service from finding it (in the `InternetArchive/processing/todo/` directory).

**Comment by TBRC-TimB** [comment]
I used the csv batch metadata upload to get this set up. 
https://archive.org/services/docs/api/internetarchive/cli.html#modifying-metadata-in-bulk

ia metadata --spreadsheet=cleanNoIndex.csv

Looks like none of them are showing up in searches, either in the terminal or on the site, 
so the whole update was a success.

**Comment by TBRC-JimK** [comment]
Damn, that's as simple as simple can be. Thanks
