### ISSUE TITLE
side effects in check-BUDA-status.txt

### ISSUE THREAD

**Issue by TBRC-JimK** [buda-base/archive-ops#61]
If the user passes in a worklist in a different directory, check-BUDA-status writes the results in that directory (e.g. `check-BUDA-status.sh inproc/arc-staging-y .` will write the results into inproc.) 
```bash
 
logFilePrefix="$logDir/${workList%.*}-${xdate}-${xtime}-IGs-IMAGES-"
+ logFilePrefix=./hoobs/arc-staging-04212020-133644-IGs-IMAGES-
```
because you use the full path of ${workList}. Run it through `basename` first.

**Comment by TBRC-Travis** [comment]
Fixed.

https://github.com/buda-base/archive-ops/commit/513d974f5abec3fcf4a2950b8fe9941744099b55
