### ISSUE TITLE
check-BUDA-status.sh doesnt work on Debian

### ISSUE THREAD

**Issue by TBRC-JimK** [buda-base/archive-ops#62]
Shebang problems. 
shebang line is  `#!/bin/sh`

which only coincidentally resolves to bash on a Mac. So when I ran this on sattva (Debian), it really ran /bin/sh, which doesn't know anything about 'function()`. double brackets or other bash extensions.

```
Mac: 

$ /bin/sh -version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.

Debian: 

~/prod/DDD/delivery-02$ /bin/sh -version
/bin/sh: 0: Illegal option -r
```

So please going forward use /usr/bin/env bash as the shebang line (note this allows the user to very precisely control which bash they use, and and insulate the script from system dependencies.

**Comment by TBRC-JimK** [comment]
Whoops. Email still in draft, so here it is shebang line is `#!/bin/sh`
which only coincidentally resolves to bash on a Mac. So when I ran this on sattva (Debian), it really ran /bin/sh, which doesn't know anything about 'function()`. double brackets or other bash extensions.

```bash
Mac: 

$ /bin/sh -version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.

Debian: 

~/prod/DDD/delivery-02$ /bin/sh -version
/bin/sh: 0: Illegal option -r
```

So please going forward use /usr/bin/env bash as the shebang line (note this allows the user to very precisely control which bash they use, and and insulate the script from system vagaries.

**Comment by TBRC-Travis** [comment]
Fixed.

https://github.com/buda-base/archive-ops/commit/01671dde3cff1b3906b89753df101eec9da10387
