### ISSUE TITLE
Better sanity check logging in syncAnywhere scripting

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/archive-ops#70]
bdrcSync.sh logs sanity checking using a temp form in [line 124](https://github.com/buda-base/archive-ops/blob/master/scripts/processing/syncAnywhere/bdrcSync.sh#L124) that makes a bit of mess.

Would suggest two changes:

1) making a separate directory for these logs
2) changing from a temp name to making a more readable log filename ie ("sanity-check-<RID>.log")

**Comment by TBRC-JimK** [comment]
You can specify a temp directory in [line 21](https://github.com/buda-base/archive-ops/blob/99ece01437995d99c5867cdcd2fb0ea39cadc6ef/scripts/processing/syncAnywhere/bdrcSync.sh#L21). There's a default value.
It doesn't help to make too many directories, and the random suffixes are required for bdrc Sync to run in parallel.
The sanity check log' path is dumped to the console, so it can be copied and pasted.

**Comment by TBRC-JimK** [comment]
I'm testing a change to file names now. Should be a fix in today.

**Comment by TBRC-Travis** [comment]
Great, thanks!

**Comment by jimk-bdrc** [comment]
I'm testing out

```bash
k:tmp$ export WD=~/tmp
k:tmp$ sanityCheck=$(mktemp -p${WD} --suffix=.log sanity-$(date +%H-%m-%S)-XXX)
k:tmp$ echo $sanityCheck
/Users/jimk/tmp/sanity-11-06-36-zzu.log
```

**Comment by jimk-bdrc** [comment]
The temp files created by a run are:
```bash
ls -1 *16-06*
sanity-16-06-34-check-Ikh.log
sanity-16-06-34-input-AC1.lst
WorkPaths-16-06-20-O3s.lst
works-failed-16-06-20-BTN.lst
```
