### ISSUE TITLE
syncAnywhere breaks cataloging entry for synced works on website

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/archive-ops#71]
syncAnywhere scripting is causing the cataloging record for synced works to disappear from the website.  For example, I just tried to syncc W8LS42203 and now it shows like this:

<img width="804" alt="breakage" src="https://user-images.githubusercontent.com/19354126/80756381-6476f580-8b00-11ea-9187-3a6f06fb8b89.png">

**Comment by TBRC-JimK** [comment]
I ran `processWeb.sh` on my site, but sent the output to a dump s3. Then W8LS42203 appeared where it should have been.
Travis is sending a couple of other works to try.

- also, download the works from my dump and from `s3://archive.tbrc.org` and compare them.

**Comment by TBRC-Travis** [comment]
> Travis is sending a couple of other works to try.

RS5:Staff/Jim/SyncTest

**Comment by TBRC-JimK** [comment]
Could not reproduce with W1KG13833
<img width="804" alt="Screen Shot 2020-05-04 at 18 01 43" src="https://user-images.githubusercontent.com/33470789/81018116-dbc6c500-8e31-11ea-9c89-56da43daa72c.png">

Could not reproduce with W8LS42182
<img width="881" alt="Screen Shot 2020-05-04 at 18 14 37" src="https://user-images.githubusercontent.com/33470789/81018935-87bce000-8e33-11ea-9025-d23c2d3c10dc.png">

Could not reproduce with W4CZ02340
<img width="881" alt="Screen Shot 2020-05-04 at 18 19 49" src="https://user-images.githubusercontent.com/33470789/81019107-f13cee80-8e33-11ea-9fc6-cb44a7f28bcb.png">

Recommend closing this issue as not reproducible

**Comment by TBRC-Travis** [comment]
I've confirmed that this is no longer an issue.  syncAnywhere is working beautifully.
