### ISSUE TITLE
Archive issue discovered during thumbnail generation -- many works with no json file on s3

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/archive-ops#76]
[json-missing.txt](https://github.com/buda-base/archive-ops/files/4610568/json-missing.txt)

**Comment by TBRC-JimK** [comment]
Quick discovery `cat errors-list.txt | parallel 'aws s3 ls s3://archive.tbrc.org/Works/$(printf {} | $SYS_MD5 | cut -c1,2)/{}/images/' | tee -a found-works.lst` on a 24 core server machine.

**Comment by TBRC-JimK** [comment]
1617 works found with images.
[found-works.txt](https://github.com/buda-base/archive-ops/files/4610830/found-works.txt)

**Comment by TBRC-JimK** [comment]
Sent to manifest process.

**Comment by TBRC-JimK** [comment]
96 works, where at least one image group not uploaded. Total 8486 un-uploaded image groups.
[vmt-warning-works.txt](https://github.com/buda-base/archive-ops/files/4615913/vmt-warnin-works.txt)

**Comment by TBRC-JimK** [comment]
Would be good to integrate the thumbnail generation process into the post-pub process.  Perhaps as part of voume-manifest-tool? Discuss with @eroux

**Comment by jimk-bdrc** [comment]
Many of the works Elie cited here hadn't even been uploaded. The ones which were uploaded were sent to v-m-t for dimensions.json creating. Recommend closing.

**Comment by eroux** [comment]
that works for me yes, thanks!
