### ISSUE TITLE
W3CN1610

### ISSUE THREAD

**Issue by TBRC-JimK** [buda-base/archive-ops#84]
Elie requested 
Could you please tell Travis that W3CN1610 was requested by one of our
partners? It's already cropped and under 400kb so if could be an easy
sync...

**Comment by TBRC-Travis** [comment]
Thanks @eroux 
I'll be sending this out with tonight's sync.

**Comment by eroux** [comment]
great, thanks a lot!

**Comment by TBRC-Travis** [comment]
@eroux This is now synced and up on our websites:  
https://www.tbrc.org/#!rid=W3CN1610
http://library.bdrc.io/show/bdr:W3CN1610

**Comment by eroux** [comment]
thanks!
