### ISSUE TITLE
Check staff@tbrc.org email list to ensure all staff are members

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/archive-ops#89]
Karma did not receive calendar invite.

**Comment by TBRC-JimK** [comment]
Will do Philip. Bringing in @TBRC-Travis

**Comment by TBRC-JimK** [comment]
Marc Agate, Nicolas, NT, and Ronn Smith are not in the Staff list. I'll add NT, but these other folks don't need to have access to the archive-ops project.  @TBRC-pmench Request you close.
