### ISSUE TITLE
Find a way to subscribe to project card creation

### ISSUE THREAD

**Issue by TBRC-JimK** [buda-base/archive-ops#91]
Or use slack

**Comment by TBRC-TimB** [comment]
Request from Travis. Keep slack notifications in their own channel separate from ao-whq

**Comment by TBRC-JimK** [comment]
Seems fine.

**Comment by TBRC-JimK** [comment]
@TBRC-Timb See [Github slack integrations](https://github.com/integrations/slack)

**Comment by TBRC-TimB** [comment]
@TBRC-JimK it looks like to get the slack bot to be able to read the repos, I need to give it permissions to access the repos. I wanted the all clear before I went and gave it those permissions.

**Comment by TBRC-TimB** [comment]
Closing foe now. Currently with the basic github Slack plugin, there is no way to get notifications for cards, since the notifications are associated with repositories, rather than with project boards.
