### ISSUE TITLE
testing slack

### ISSUE THREAD

**Issue by TBRC-TimB** [buda-base/archive-ops#95]
testing to see if slack notifications work

**Comment by TBRC-JimK** [comment]
How very nice. So I'll expect this comment to also pop up in Slack.

**Comment by TBRC-JimK** [comment]
OK, now with integration I expect this comment to pop up in slack

**Comment by TBRC-TimB** [comment]
tracking spreadsheet for reprocessing. 
https://docs.google.com/spreadsheets/d/1Z88k6PvHci8vgSo5-RocWlwHQyMTzX3yf42YcBGnLn4/edit?usp=sharing

**Comment by TBRC-TimB** [comment]
Testing for slack notification.
