### ISSUE TITLE
sync request: W1KG26108

### ISSUE THREAD

**Issue by eroux** [buda-base/archive-ops#99]
Hello AO,

Not urgent, but for the next batch of OCR. it would be quite useful to sync the images in `ReadyToProcess/Taiwan/Other-Taiwan-12/W1KG26108`. In our tests they bring a real benefit to the OCR result compared to the other scans we have. It should also be quite straightforward to process as it's already cropped and under 400k.

Thanks in advance

**Comment by TBRC-Travis** [comment]
@eroux are you sure you have the right work number?  I looked in ReadyToProcess/Taiwan/Other-Taiwan-12/W1KG26108 and this is not a straightforward work.  There are many volumes with lots of PDFs all of which are quite large.

**Comment by eroux** [comment]
it's a Kangyur so about 100 volumes yes. I looked at volume 1 which has cropped images, it's 140MB for 570 images so 250kb / image... I expected all volumes to be similar. Volume 2 is twice as large but I'm not sure it's wort reprocessing the images.

So it still seems quite straightforward to me, I imagine the processing as:
- extracting the jpg from the PDF
- batch rename
- sync

what am I missing?

**Comment by TBRC-Travis** [comment]
You're correct.  Your original comment made it sound like this was just a matter of syncing the files without needing any processing, so I was just making sure I was looking at the right one.

**Comment by TBRC-Travis** [comment]
@eroux since you marked this as "not urgent" I'm putting this in my queue for next week.  It should be synced by no later then next Friday.  Will keep you posted.

**Comment by eroux** [comment]
sure, perfect!

**Comment by TBRC-Travis** [comment]
Hi @eroux, I finished processing this work yesterday but ran into some issues with audit tool when trying to sync it last night.  It uncovered some really funky problems with the ImageAttributeTest in audit tool that @jimk-bdrc will need to look at.  Jim and I will tackle this when he gets back from vacation next week.  New ETA for this is next Wednesday.  Hope that's okay.

**Comment by eroux** [comment]
sure, thanks for the update!

**Comment by TBRC-Travis** [comment]
@eroux this is now synced and online:  https://www.tbrc.org/#!rid=W1KG26108

Post-processing is still underway so I imagine you'll see this up on library.bdrc.io by tomorrow.

**Comment by eroux** [comment]
thanks!
